/* eslint-disable @typescript-eslint/no-explicit-any */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate this file.

import type { GenericDataModel, GenericDocument, GenericTableInfo } from "convex/server";
import type { GenericId } from "convex/values";

export type DataModel = GenericDataModel;
export type Document<TableName extends string> = GenericDocument & { _id: Id<TableName> };
export type Id<TableName extends string> = GenericId<TableName>;
export type TableInfo = GenericTableInfo;

export type TableNames =
  | "users"
  | "userSettings"
  | "projects"
  | "documents"
  | "revisions"
  | "aiFeedback"
  | "personas"
  | "spendingSessions"
  | "authAccounts"
  | "authRefreshTokens"
  | "authSessions"
  | "authVerificationCodes"
  | "authVerifiers"
  | "authRateLimits";
