/* eslint-disable */
// This file is auto-generated by Convex.
// Run `npx convex dev` to regenerate this file.

import {
  ActionBuilder,
  HttpActionBuilder,
  MutationBuilder,
  QueryBuilder,
  GenericActionCtx,
  GenericMutationCtx,
  GenericQueryCtx,
  GenericDatabaseReader,
  GenericDatabaseWriter,
} from "convex/server";
import type { DataModel } from "./dataModel.js";

export type QueryCtx = GenericQueryCtx<DataModel>;
export type MutationCtx = GenericMutationCtx<DataModel>;
export type ActionCtx = GenericActionCtx<DataModel>;

export type DatabaseReader = GenericDatabaseReader<DataModel>;
export type DatabaseWriter = GenericDatabaseWriter<DataModel>;

export const query = ((fn: unknown) => fn) as QueryBuilder<DataModel, "public">;
export const internalQuery = ((fn: unknown) => fn) as QueryBuilder<DataModel, "internal">;
export const mutation = ((fn: unknown) => fn) as MutationBuilder<DataModel, "public">;
export const internalMutation = ((fn: unknown) => fn) as MutationBuilder<DataModel, "internal">;
export const action = ((fn: unknown) => fn) as ActionBuilder<DataModel, "public">;
export const internalAction = ((fn: unknown) => fn) as ActionBuilder<DataModel, "internal">;
export const httpAction = ((fn: unknown) => fn) as HttpActionBuilder;
